apiVersion: v1
kind: Namespace
metadata:
  name: test-apps
  labels:
    environment: development
    project: ai-fitness
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
  namespace: test-apps
  labels:
    app: hello-world
    environment: development
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
        environment: development
    spec:
      containers:
      - name: hello-world
        image: nginx:1.21-alpine
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: html
        configMap:
          name: hello-world-html
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hello-world-html
  namespace: test-apps
data:
  index.html: |
    <!DOCTYPE html>
    <html>
    <head>
        <title>AI Fitness Dev - EKS Test</title>
        <style>
            body { 
                font-family: Arial, sans-serif; 
                background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
                margin: 0;
                padding: 20px;
                color: white;
            }
            .container { 
                max-width: 800px; 
                margin: 0 auto; 
                text-align: center; 
                padding: 40px;
                background: rgba(255,255,255,0.1);
                border-radius: 15px;
                backdrop-filter: blur(10px);
            }
            h1 { color: #fff; margin-bottom: 30px; }
            .info { 
                background: rgba(255,255,255,0.2); 
                padding: 20px; 
                border-radius: 10px; 
                margin: 20px 0;
            }
            .status { 
                color: #4CAF50; 
                font-weight: bold; 
                font-size: 24px;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <h1>🎉 AI Fitness Dev EKS Cluster</h1>
            <div class="status">✅ CLUSTER OPERATIONAL</div>
            
            <div class="info">
                <h3>Cluster Information</h3>
                <p><strong>Cluster:</strong> ai-fitness-dev</p>
                <p><strong>Region:</strong> us-east-1</p>
                <p><strong>Environment:</strong> Development</p>
                <p><strong>Node Type:</strong> t3.medium (Spot)</p>
            </div>
            
            <div class="info">
                <h3>Pod Information</h3>
                <p><strong>Namespace:</strong> test-apps</p>
                <p><strong>Deployment:</strong> hello-world</p>
                <p><strong>Replicas:</strong> 2</p>
                <p><strong>Image:</strong> nginx:1.21-alpine</p>
            </div>
            
            <div class="info">
                <h3>Next Steps</h3>
                <p>🔧 Deploy your AI fitness applications</p>
                <p>📊 Set up monitoring and observability</p>
                <p>🚀 Configure CI/CD pipelines</p>
                <p>💰 Monitor costs and optimize resources</p>
            </div>
            
            <p style="margin-top: 40px; opacity: 0.8;">
                <small>Deployed on: $(date)</small>
            </p>
        </div>
    </body>
    </html>
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
  namespace: test-apps
  labels:
    app: hello-world
spec:
  selector:
    app: hello-world
  ports:
  - port: 80
    targetPort: 80
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-ingress
  namespace: test-apps
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: hello-world.ai-fitness-dev.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hello-world-service
            port:
              number: 80